[project]
name = "ai-newsletter"
version = "0.1.0"
dependencies = [
    "newspaper3k>=0.2.8",
    "feedparser>=6.0.11",
    "selenium>=4.31.0",
    "click>=8.0.0"
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"