[project]
name = "ai-newsletter"
version = "0.1.0"
dependencies = [
    "newspaper3k>=0.2.8",
    "feedparser>=6.0.11",
    "click>=8.0.0"
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
requests-html = "^0.10.0"
newspaper3k = "^0.2.8"
feedparser = "^6.0.0"
beautifulsoup4 = "^4.11.0"
python-dotenv = "^1.0.0"
nltk = "^3.6.2"
openai = "^1.3.0"
pandas = "^2.1.0"
pytz = "^2024.1"
python-dateutil = "^2.8.2"
certifi = "^2024.2.2"
urllib3 = "^2.2.0"
cryptography = "^42.0.5"
pyOpenSSL = "^24.0.0"
psutil = "^5.9.0"
lxml = {version = "^5.1.0", extras = ["html_clean"]}
filelock = "^3.12.0"
backoff = "^2.2.1"
concurrent-log-handler = "^0.9.20"

[tool.poetry.dev-dependencies]
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
pytest-mock = "^3.12.0"