name: Daily AI Newsletter

on:
  schedule:
    - cron: '14 8 * * *'  # Run at 8:00 AM Central Time daily
  workflow_dispatch:       # Allow manual trigger for testing

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout newsletter code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set DATE and newsletter URL
        run: |
          DATE=$(date +%Y-%m-%d)
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "NEWSLETTER_URL=https://samuelrumbley.com/newsletters/$DATE.html" >> $GITHUB_ENV
      
      - name: Generate newsletter
        env:
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
          NEWSLETTER_DOMAIN: ${{ secrets.NEWSLETTER_DOMAIN }}
          NEWS_SOURCE: ${{ secrets.NEWS_SOURCE }}
        run: |
          echo "Starting newsletter script..."
          python main.py
          
      - name: Create output directory
        run: |
          mkdir -p output
          cp email.html output/newsletter.html
      
      - name: Checkout GitHub Pages repo
        uses: actions/checkout@v3
        with:
          repository: caninecrew/caninecrew.github.io
          token: ${{ secrets.GH_PAT }}
          path: pages-repo

      - name: Deploy newsletter HTML
        run: |
          mkdir -p pages-repo/newsletters
          cp output/newsletter.html "pages-repo/newsletters/${{ env.DATE }}.html"
          cd pages-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add newsletters/
          git commit -m "Deploy newsletter for ${{ env.DATE }}" || echo "No changes"
          git push

      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newsletter-logs
          path: |
            logs.txt
            logs/*.log
          retention-days: 7

      - name: Report completion status
        if: success()
        run: |
          echo "Newsletter generated and deployed successfully at $(date)"
          echo "Available at ${{ env.NEWSLETTER_URL }}"